### ISSUE TITLE
Support subsequent commits triggering a preview

### ISSUE THREAD

**Issue by lukqw** [localstack/setup-localstack#35]
## Context
When triggering a preview deployment of your repository, while one is already live, the action will fail with an error
> API response: {"error": true, "message": "compute.already_exists"}

This is because an instance with the name already exists, due to the previous commit triggering a deployment.

Instead of erroring, the action should shut down the old one, and create a new one. (Thought: maybe this could be configurable? I.e. `replace-old-preview` as an argument?)

Another thought to consider: What if I have two PRs in two repos with the same number at the same time - the current naming strategy would end up generating `preview-1` and `preview-1` across both repos. 
Maybe there's another way we can prevent these naming collisions in the first place?

**Comment by remotesynth** [comment]
I agree on this. I ran into this problem multiple times as I'd forget the instance started even though my deploy to that instance failed. It would be nice if the Action could configure options on that instance too (example, how long it should live). Right now, if something fails, an empty instance is spun up that consumes 30 minutes.

**Comment by lakkeger** [comment]
Reasonable requests, we discuss the necessary steps on a different channel and start to implement this feature/fix.

**Comment by lukqw** [comment]
closing as implemented in https://github.com/localstack/setup-localstack/pull/36
